baseURL: "https://elo-issam.netlify.app"
languageCode: "fr-fr"
title: "ELO IssaPortfolio"
theme: hugo-profile

Paginate: 3
disqusShortname:
googleAnalytics:

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1

    #Dropdown menu
    - identifier: dropdown
      title: Example dropdown menu
      name: Dropdown
      weight: 2
    - identifier: dropdown1
      title: example dropdown 1
      name: example 1
      url: /#
      parent: dropdown
      weight: 1
    - identifier: dropdown2
      title: example dropdown 2
      name: example 2
      url: /#
      parent: dropdown
      weight: 2

params:
  title: "ELO Issam"
  description: Portfolio Issam
  favicon: "/fav.png"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Bonjour, Je suis"
    title: "Issam."
    subtitle: "Etudiant BTS SIO SLAM"
    content: "Passionné par les nouvelles technologies et  intéressé par le développement applicatif, je compte poursuivre mes études dans ce domaine."
    image: /images/hero.png
    button:
      enable: true
      name: "Resume"
      url: "#"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/ELO-I
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/issaml/
      customIcons:
        - icon: /fav.png
          url: "https://example.com"

  # About
  about:
    enable: true
    title: "A propos"
    image: "/images/me.png"
    content: |-
      Actuellement étudiant au lycée Saint-Michel à Annecy, j'effectue un BTS SIO Option SLAM (Service Informatique aux Organisations option solutions logicielles et applications métiers )

      J'ai obtenu un BAC professionnel SN RISC au lycée Saint-Vincent-de-Paul à Collonges-sous-Salève où j'ai déjà effectué plusieurs stages en entreprises dans le domaine du réseau.

      J'apprends aujourd'hui la programmation Back-end en cours et en autodidacte.

    skills:
      enable: true
      title: "Les technologies que j'utilise régulièrement"
      items:
        - "HTML/CSS/JS"
        - "PHP"
        - "Symfony"
        - "C#/WPF"
        - "Python"
        - "MySQL"

  # Experience
  experience:
    enable: true
    items:
      - job: "Dévelopeur Back-End Django"
        company: "Little Yes"
        companyUrl: "https://little-yes.com/"
        date: "Jan 2022 - Fev 2022"
        info:
          enable: true
          content: J'y étais en tant que stagiaire.
        content: |
          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

          - Lead backend developer for a product.
          - Created a frontend design for a product."

      - job: "Développeur Python"
        company: "Cosmecode"
        companyUrl: "https://www.cosmecode.com/"
        date: "May 2021 - Jun 2021"
        info:
          enable: true
          content: J'y étais en tant que stagiaire.
        content: |
          Réalisation de WEB-Scrapping avec le framework Scrappy

  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "BTS SIO option SLAM"
        school:
          name: "Saint Michel Annecy"
          url: "https://www.st-michel.fr/"
        date: "2020 - 2022"
        content: |-
          💻 Développement:
            - 🔶 Programmation 
              - 🔸 Applications Windows: C# (Windows Forms et console)
              - 🔸 Applications Windows: C# (Windows Forms et console)
              - 🔸 Algorithmie : Python 
              - 🔸 Environnement : Visual Studio | Suite Jetbrains et WampServer | Laragon
            - 🔶 Système de Gestion de Bases de Données:
              - 🔸 MySQL : installation et configuration
              - 🔸 SQLServer : installation et configuration
              - 🔸 Requêtes SQL (requêtes simples, sous requêtes, jointure, groupement)
            - 🔶 Modélisation
              - 🔸 Merise (Modèle Conceptuel de Données et modèle relationnel)
              - 🔸 U.M.L. (diagramme de classes et de séquence)
              - 🔸 Use Case

      - title: "Baccalauréat professionnel systèmes électroniques numériques"
        school:
          name: "Lycée Professionnel Saint Vincent de Paul"
          url: "https://www.saint-vincent74.fr/"
        date: "2017 - 2020"
        content: |-
          Compétences acquises :
          - 🔹 Administration système et Administration des réseaux
          - 🔹 Excellente connaissance de l’environnement Microsoft (Server 2012 r2/2016/2019/, Windows 10, Windows 7)
          - 🔹 Excellente connaissance de l’environnement CISCO ( Switch, Routeur configuration Console, Vlan etc.) 
          - 🔹 Connaissance réseaux : TCP\IP, DHCP, DNS, SMB, NAT, POP, IMAP, SMTP, SSL, TLS
          - 🔹 Annuaire Active Directory, des GPO, de IIS, Suite Office.
          - 🔹 Connaissance sur les environnements : Vmware, VirtualBox, Tse
          - 🔹 Mise en place de Script Powershell

  # Achievements
  achievements:
    enable: true
    items:
      - title: Certification Pix
        content: Pix
        url: https://example.com

      - title: MOOC L'Atelier RGPD
        content: CNIL - Commission Nationale de l'Informatique et des Libertés
        url: https://example.com

      - title: MOOC SecNumacadémie
        content: ANSSI - Agence nationale de la sécurité des systèmes d'information
        url: https://example.com

  # projects
  projects:
    enable: true
    items:
      - title: AP
        content: Réalisation d'un site web pour un musée
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://elo-issam.netlify.app

      - title: AP 2
        content: Réalisation d'un site web pour un musée
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://elo-issam.netlify.app

      - title: AP 3
        content: Réalisation d'un site web pour un musée
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://elo-issam.netlify.app

  #Contact
  contact:
    enable: true
    content: N'hésitez pas à me contacter pour toute question, problème, etc...
    email: issam.el.ouiazzani@gmail.com
    btnName: Contacter moi

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/ELO-I
      linkedin: https://www.linkedin.com/in/issaml/
